# Generated by Django 4.1.7 on 2023-05-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0002_alter_categories_category_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
