# Generated by Django 4.1.7 on 2023-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0003_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='deliveries',
            constraint=models.UniqueConstraint(fields=('amount',), name='amount_of_product'),
        ),
    ]
