# Generated by Django 4.1.7 on 2023-05-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0005_alter_item_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliveries',
            name='amount_of_product',
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shp.item', to_field='item_name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
