# Generated by Django 4.1.7 on 2023-06-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0006_remove_deliveries_amount_of_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
