# Generated by Django 4.1.7 on 2023-06-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0008_cheque_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='item_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shp.item', to_field='item_name'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
