# Generated by Django 4.1.7 on 2023-06-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shp', '0009_alter_cheque_item_name_alter_cheque_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
